openapi: 3.0.0
info:
  title: Data Catalog Versioning API
  version: '1.0'
  description: |-
    The asset versioning service of the Data Catalog application.

    Provides API endpoints to create, delete and retrieve asset versions. The access rights to an asset's version are the same as the right to the asset itself.

    The versions cannot be modified, only deleted.
  contact:
    name: Szilárd Tumó
    email: szilardtumo@stud.ubbcluj.ro
servers:
  - url: 'https://versioningservice.azurewebsites.net'
paths:
  '/assets/{assetId}/versions':
    parameters:
      - schema:
          type: string
        name: assetId
        in: path
        required: true
        description: The ID of the asset.
    get:
      summary: List the versions of an asset
      tags:
        - Version
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./definitions/VersionResponse.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ./definitions/ErrorResponse.yaml
      operationId: getAssetVersions
      description: |-
        Lists all the available versions of the asset.

        Requires access rights to the asset itself, to be able to retrieve the version.

        Possible response codes:
        - `404`: The asset was not found.
        - `200`: The version was returned in the HTTP body.
    post:
      summary: ''
      operationId: createAssetVersion
      responses:
        '201':
          description: Created
        '404':
          description: Not Found
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                $ref: ./definitions/ErrorResponse.yaml
      description: |-
        Creates a new version of the asset, with the current content of the asset.

        Requires access rights to the asset itself, to be able to create a new version.

        Possible response codes:
        - `404`: The asset was not found.
        - `422`: The HTTP request body is invalid. Detailed explanation can be found in the response body.
        - `201`: The version was created successfully.
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./definitions/VersionRequest.yaml
      tags:
        - Version
  '/assets/{assetId}/versions/{name}':
    parameters:
      - schema:
          type: string
        name: assetId
        in: path
        required: true
        description: The ID of the asset.
      - schema:
          type: string
        name: name
        in: path
        required: true
        description: The name of the asset version.
    get:
      summary: A version of an asset
      tags:
        - Version
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./definitions/VersionResponse.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ./definitions/ErrorResponse.yaml
      operationId: getAssetVersion
      description: |-
        Returns the required version of the asset.

        Requires access rights to the asset itself, to be able to retrieve the version.

        Possible response codes:
        - `404`: The asset, or the asset version was not found.
        - `200`: The version was returned in the HTTP body.
      parameters: []
    delete:
      summary: ''
      operationId: deleteAssetVersion
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ./definitions/ErrorResponse.yaml
      description: |-
        Deletes the sepcified version of the asset.

        Responds with `404` if the asset or the version is not found. Details about the failure in the `message` field of the error response.
      security:
        - JWT: []
      tags:
        - Version
components:
  schemas:
    VersionRequest:
      $ref: ./definitions/VersionRequest.yaml
    VersionResponse:
      $ref: ./definitions/VersionResponse.yaml
    ErrorResponse:
      $ref: ./definitions/ErrorResponse.yaml
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: Bearer <token>
      description: Authentication is made by the JWT token sent in the Authorization header of the request.
tags:
  - name: Version
    x-displayName: Version Management
security:
  - JWT: []
